name: Debugging Secret context
on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump secret context
        env:
          SECRET_CONTEXT: ${{ toJson(secret) }}
        run: echo "$SECRET_CONTEXT"