name: Debugging Secret context
on: push

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump secrets context
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
        run: echo "$SECRETS_CONTEXT"